it.only('login test',function()
{
    cy.visit ("http://localhost:3000/login")   
    cy.get('[data-test="login-form"]').click()
    cy.get('.signup-link').click()
   cy.get('.navbar').click()
   //cy.get('data-test="source-button"').click()
   //cy.get('[data-test="drive-button"]').click()   
   //cy.get('#hamburger > svg > path').click()
   //cy.get('#cypressDrive').click()
   cy.get('[data-test="drive-button"]').click()
})
